### ISSUE TITLE
Task not found

### ISSUE THREAD

**Issue by bradfrost** [EvanLovely/grunt-pattern-lab-component-builder#2]
Thanks for the clarification from #1. 

I've installed the package from npm, and have added the instructions to `Gruntfile.js`. I also added `pattern-lab-component-builder` to the registerTask array, something like:
`grunt.registerTask('default', ['pattern-lab-component-builder']);`

When I run grunt, I get this message: "Warning: Task "pattern-lab-component-builder" not found. Use --force to continue."

Any ideas on why this might not be working?

Thanks!

**Comment by EvanLovely** [comment]
@bradfrost Swap your `-` for `_` in the name of the plugin; that should do it! I've tested this and all should be working. Don't hesitate to ping me back if it's not!

**Comment by bradfrost** [comment]
Hmmmm, I'm still getting errors.

![ember](https://cloud.githubusercontent.com/assets/383701/6477937/297aad82-c1f7-11e4-8a17-b75c6167340c.png)

Here's what my Gruntfile looks like:

```
grunt.initConfig({
...
pattern_lab_component_builder: {
            colors: {
              options: {
                regex: "^\\$color--.*",
                allow_var_values: false
              },
              src: 'scss/global/variables/_colors.scss',
              dest: 'source/_patterns/00-atoms/01-global/00-colors.json'
            },
            fonts: {
              options: {
                'regex': "^\\$type.*"
              },
              src: "scss/global/variables/_type-sizes.scss",
              dest: "source/_patterns/00-atoms/02-text/02-type-sizes.json"
            }
        }
...
});

grunt.registerTask('default', ['sass', 'watch', 'autoprefixer', 'connect:server', 'jekyll', 'shell:patternlab', 'pattern_lab_component_builder']);
```

Any ideas?

**Comment by bradfrost** [comment]
Ah, I looked in the `node_modules` directory and updated the path to register the task to `grunt.loadNpmTasks('grunt-pattern-lab-component-builder');`

Appears to be loading now. Now the fun part, trying to make it work!

Thanks again.
